name = "GeometricMatrixAlgebras"
uuid = "6cba012c-fa21-4645-b88a-8002027d6abd"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.5"
StaticArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]